# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b26a618d185c261b8011dbbd316e2d81485ca2f4c4c57c1e1872532f08f36eef5183697168b545d3596ff873006b61ad13510884858c25736a2d6ffe85f4894

test:
  secret_key_base: 5bd9312866292f96bdcfbb682e019b198fff1896f63cda7b9b1f4e013161be2ab3e22a4a1fc9d25920bdcab61ac9fcd18fc41c9bf1c9a2358366bf9a3bb7574b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
